[package]

name = "template"
version = "0.0.1"
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Go's text/template package for Rust."
homepage = "https://github.com/jimmycuadra/template"
